repos:
# -   repo: https://github.com/pycqa/isort
#     rev: 5.10.1
#     hooks:
#       - id: isort
#         name: isort (python)

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black
      language_version: python3.9

# built-in pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    # - id: check-json
    - id: check-added-large-files
