feature_dim: 6
epochs: 5
learning_rate: 0.05
learning_rate_weight_decay: 0.0001
batch_size: 16
pointcloud_input_size: 10000
save_frequency: 1
class_weights: [0.64, 0.80, 0.67, 0.99, 1.00, 0.98, 1.00, 0.95, 0.99, 0.99, 0.98, 1.00, 1.00]

# set data and output path in environment
data_path: /mnt/shared/personal/pointcloud_dl/data/sensat_urban/grid_0.2
output_path: /mnt/shared/personal/pointcloud_dl/data/output
