feature_dim: 6
epochs: 5
learning_rate: 0.5
learning_rate_weight_decay: 0.0001
batch_size: 16
pointcloud_input_size: 80000
save_frequency: 1

# set data and output path in environment
data_path: /mnt/shared/personal/pointcloud_dl/data/sensat_urban/grid_0.2
output_path: /mnt/shared/personal/pointcloud_dl/data/output
